language: node_js
node_js:
  - "8"

script:
  - "npm i"
  - "npm run build"
  - "npm run test"
  - "echo $TRAVIS_BRANCH"
  - "echo $AWS_KEY_ID"

deploy:
  provider: s3
  access_key_id: "$AWS_KEY_ID"
  secret_access_key: "$AWS_KEY_SECRET"
  bucket: "static-scania-com/stencil/$TRAVIS_BRANCH/"
  on:
    branch: master

deploy:
  provider: npm
  email: "andreas.wikstrom@scania.com"
  api_key: "$NPM_ACCESS_KEY"
  on:
    branch: master
